//! ACE 配置加载器
//!
//! 负责从独立的配置文件加载ACE配置，支持自动创建默认配置。

use anyhow::Context;
use anyhow::Result;
use serde::Deserialize;
use serde::Serialize;
use std::path::Path;
use std::path::PathBuf;
use tokio::fs;

use super::types::ACEConfig;

/// ACE 配置文件名
pub const ACE_CONFIG_FILENAME: &str = "codeACE-config.toml";

/// 默认配置文件模板
const DEFAULT_CONFIG_TOML: &str = r#"# ACE (Agentic Coding Environment) Configuration
#
# This file is automatically generated on first run.
# ACE learns from your coding sessions and provides intelligent context suggestions.

# ============================================================================
# Core Settings
# ============================================================================

[ace]
# Enable or disable ACE framework
enabled = true

# Storage path for learned knowledge (supports ~)
storage_path = "~/.codeACE/ace"

# Maximum number of entries before auto-archiving
max_entries = 500

# ============================================================================
# Reflector Settings (Knowledge Extraction)
# ============================================================================

[ace.reflector]
# Extract code patterns (e.g., file operations, build workflows)
extract_patterns = true

# Extract tool usage information
extract_tools = true

# Extract error handling strategies
extract_errors = true

# ============================================================================
# Context Settings (Knowledge Retrieval)
# ============================================================================

[ace.context]
# Maximum number of recent entries to consider
max_recent_entries = 10

# Include all successful cases in context search
include_all_successes = true

# Maximum characters for context injection
max_context_chars = 4000
"#;

/// ACE 配置的 TOML 表示（用于序列化/反序列化）
#[derive(Debug, Clone, Serialize, Deserialize)]
struct ACEConfigToml {
    ace: ACEConfig,
}

/// ACE 配置加载器
pub struct ACEConfigLoader {
    config_path: PathBuf,
}

impl ACEConfigLoader {
    /// 创建配置加载器
    ///
    /// # 参数
    /// - `codex_home`: Codex home 目录（通常是 ~/.codeACE）
    pub fn new(codex_home: &Path) -> Self {
        let config_path = codex_home.join(ACE_CONFIG_FILENAME);
        Self { config_path }
    }

    /// 加载配置（如果不存在则自动创建）
    ///
    /// 工作流程：
    /// 1. 检查配置文件是否存在
    /// 2. 不存在则创建默认配置
    /// 3. 读取并解析配置
    /// 4. 返回配置或错误
    pub async fn load_or_create(&self) -> Result<ACEConfig> {
        // 1. 检查文件是否存在
        if !self.config_path.exists() {
            tracing::info!(
                "ACE config not found at {:?}, creating default config...",
                self.config_path
            );
            self.create_default_config().await?;
        }

        // 2. 加载配置
        self.load().await
    }

    /// 加载现有配置
    async fn load(&self) -> Result<ACEConfig> {
        let content = fs::read_to_string(&self.config_path)
            .await
            .with_context(|| format!("Failed to read ACE config from {:?}", self.config_path))?;

        let config_toml: ACEConfigToml = toml::from_str(&content)
            .with_context(|| format!("Failed to parse ACE config from {:?}", self.config_path))?;

        tracing::debug!("Loaded ACE config: enabled={}", config_toml.ace.enabled);

        Ok(config_toml.ace)
    }

    /// 创建默认配置文件
    async fn create_default_config(&self) -> Result<()> {
        // 确保父目录存在
        if let Some(parent) = self.config_path.parent() {
            fs::create_dir_all(parent)
                .await
                .with_context(|| format!("Failed to create config directory: {:?}", parent))?;
        }

        // 写入默认配置
        fs::write(&self.config_path, DEFAULT_CONFIG_TOML)
            .await
            .with_context(|| {
                format!(
                    "Failed to write default ACE config to {:?}",
                    self.config_path
                )
            })?;

        tracing::info!("Created default ACE config at {:?}", self.config_path);

        Ok(())
    }

    /// 保存配置（用于CLI修改配置）
    pub async fn save(&self, config: &ACEConfig) -> Result<()> {
        let config_toml = ACEConfigToml {
            ace: config.clone(),
        };

        let content = toml::to_string_pretty(&config_toml)
            .with_context(|| "Failed to serialize ACE config")?;

        fs::write(&self.config_path, content)
            .await
            .with_context(|| format!("Failed to write ACE config to {:?}", self.config_path))?;

        tracing::info!("Saved ACE config to {:?}", self.config_path);

        Ok(())
    }

    /// 获取配置文件路径
    pub fn config_path(&self) -> &Path {
        &self.config_path
    }
}

/// 便捷函数：从 CODEACE_HOME 加载配置
///
/// # 参数
/// - `codex_home`: Codex home 目录路径
pub async fn load_ace_config(codex_home: &Path) -> Result<ACEConfig> {
    let loader = ACEConfigLoader::new(codex_home);
    loader.load_or_create().await
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[tokio::test]
    async fn test_create_default_config() {
        let temp_dir = TempDir::new().unwrap();
        let loader = ACEConfigLoader::new(temp_dir.path());

        // 配置文件应该不存在
        assert!(!loader.config_path().exists());

        // 加载应该自动创建
        let config = loader.load_or_create().await.unwrap();

        // 验证默认值
        assert!(config.enabled); // 默认启用
        assert_eq!(config.max_entries, 500);
        assert!(config.reflector.extract_patterns);
        assert!(config.reflector.extract_tools);
        assert!(config.reflector.extract_errors);

        // 文件应该已创建
        assert!(loader.config_path().exists());
    }

    #[tokio::test]
    async fn test_load_existing_config() {
        let temp_dir = TempDir::new().unwrap();
        let loader = ACEConfigLoader::new(temp_dir.path());

        // 创建自定义配置
        let custom_config = r#"
[ace]
enabled = false
storage_path = "/custom/path"
max_entries = 100

[ace.reflector]
extract_patterns = false
extract_tools = true
extract_errors = false

[ace.context]
max_recent_entries = 5
include_all_successes = false
max_context_chars = 2000
"#;

        fs::write(loader.config_path(), custom_config)
            .await
            .unwrap();

        // 加载配置
        let config = loader.load_or_create().await.unwrap();

        // 验证自定义值
        assert!(!config.enabled);
        assert_eq!(config.storage_path, "/custom/path");
        assert_eq!(config.max_entries, 100);
        assert!(!config.reflector.extract_patterns);
        assert!(config.reflector.extract_tools);
        assert!(!config.reflector.extract_errors);
        assert_eq!(config.context.max_recent_entries, 5);
        assert!(!config.context.include_all_successes);
        assert_eq!(config.context.max_context_chars, 2000);
    }

    #[tokio::test]
    async fn test_save_config() {
        let temp_dir = TempDir::new().unwrap();
        let loader = ACEConfigLoader::new(temp_dir.path());

        // 创建自定义配置
        let mut config = ACEConfig::default();
        config.enabled = false;
        config.max_entries = 999;

        // 保存
        loader.save(&config).await.unwrap();

        // 重新加载验证
        let loaded = loader.load().await.unwrap();
        assert!(!loaded.enabled);
        assert_eq!(loaded.max_entries, 999);
    }
}
